Repository rsksmart/rif-marketplace-ui, pull requests merged in 2020-11, with the labels that each got.

#443 feat(storage): adds ability to payout funds for provider
  src/components/organisms/storage/agreements/utils.tsx
  src/components/organisms/storage/myoffers/ActiveContracts.tsx
  src/components/templates/ProgressOverlay.tsx
  src/constants/strings.ts
  src/contracts/Staking.ts
  src/contracts/storage/contract.ts
Labels: enhancement

#481 fix: enables CopyTooltip in addresses and uses agreementReference
  src/components/molecules/AddressItem.tsx
  src/components/organisms/storage/agreements/utils.tsx
Labels: bug

#476 fix: avoids negative values on inputs (fixes #456) and fixes linter w
  src/components/organisms/storage/sell/EditOfferStepper.tsx
  src/components/organisms/storage/sell/EditableBillingPlan.tsx
  src/components/organisms/storage/sell/GeneralFeatures.tsx
Labels: bug

#492 feat(storage): adds ability to check for whitelisted storage providers
  src/components/organisms/storage/staking/Staking.tsx
  src/components/pages/storage/StorageRoutes.tsx
  src/components/pages/storage/sell/StorageSellPage.tsx
  src/context/Services/storage/Context.tsx
  src/context/Services/storage/actions.ts
  src/context/Services/storage/global/actions.ts
  src/context/Services/storage/global/interfaces.ts
  src/context/Services/storage/index.ts
  src/context/Services/storage/interfaces.ts
Labels: enhancement

#537 fix: fix first failing tx for staking
  src/components/organisms/storage/staking/Staking.tsx
  src/contracts/rns/Marketplace.ts
  src/contracts/storage/Staking.ts
  src/contracts/storage/Storage.ts
  src/contracts/tokens/rif/erc20.ts
  src/contracts/tokens/rif/erc677.ts
Labels: bug

#545 fix(storage): fixes offer creation
  src/components/pages/storage/sell/StorageSellPage.tsx
Labels: bug

#546 fix(storage): rounds down listed size on offer creation
  src/contracts/storage/utils.ts
Labels: bug

#547 fix(general): rskjs-util library for checksum
  package-lock.json
  package.json
  src/utils/stringUtils.ts
Labels: P0 - Critical, bug
