Repository rsksmart/rif-marketplace-ui, pull requests merged in 2020-10, with the labels that each got.

#411 feat(storage): adds agreement details modal
  src/components/molecules/AddressItem.tsx
  src/components/pages/storage/myPurchases/Page.tsx
  src/components/pages/storage/myPurchases/utils.tsx
Labels: task

#418 Bumps rif-ui version
  package-lock.json
  package.json
Labels: dependencies

#419 fix: filters by account on my offers and cleans up on unmount
  src/components/pages/storage/myoffers/StorageMyOffersPage.tsx
Labels: bug

#420 fix: cleans up context on offers page and my offers will unmount
  src/components/pages/storage/buy/StorageOffersPage.tsx
  src/components/pages/storage/myoffers/StorageMyOffersPage.tsx
Labels: bug

#435 fix(storage): agreements monthly price calc w/ size
  src/api/rif-marketplace-cache/storage/agreements.ts
  src/context/storage/mypurchases/renew/Context.tsx
Labels: P0 - Critical, bug

#433 refactor: makes staking page and progress overlay compatible
  src/components/organisms/storage/staking/Staking.tsx
  src/components/templates/ProgressOverlay.tsx
Labels: refactor

#436 fix(storage): fixes renewal date calculation
  src/components/organisms/storage/agreements/utils.tsx
  src/context/storage/buy/checkout/Context.tsx
  src/context/storage/mypurchases/renew/Context.tsx
  src/utils/dateUtils.ts
Labels: P1 - High, bug

#438 chore: updates rif-ui version
  package-lock.json
  package.json
Labels: dependencies

#444 fix: fixes remaining size calculation for storage offers
  src/components/organisms/storage/myoffers/ExpandableOffer.tsx
Labels: bug
