Repository rsksmart/rif-marketplace-ui, pull requests merged in 2020-06, with the labels that each got.

#191 feat: Adds the ability to listen to and wait for transaction confirmations
  .prettierrc.json
  src/App.tsx
  src/api/rif-marketplace-cache/config.ts
  src/api/rif-marketplace-cache/confirmationsController.ts
  src/components/organisms/TransactionInProgressPanel.tsx
  src/components/organisms/rns/sell/MyDomains.tsx
  src/components/organisms/rns/sell/MyOffers.tsx
  src/components/organisms/rns/sell/SoldDomains.tsx
  src/components/pages/rns/buy/DomainOffersCheckoutPage.tsx
  src/components/pages/rns/buy/DomainOffersPage.tsx
  src/components/pages/rns/cancel/CancelDomainCheckoutPage.tsx
  src/components/pages/rns/sell/DomainCheckoutPage.tsx
  src/store/App/AppStore.tsx
  src/store/App/appReducer.ts
  src/store/Blockchain/BlockchainStore.tsx
  src/store/Blockchain/blockchainActions.ts
  src/store/Blockchain/blockchainReducer.ts
  src/store/Market/marketActions.ts
  src/store/Market/marketReducer.ts
Labels: task

#203 Applied latest rif-ui changes to withAccount HOC
  src/components/atoms/LoginModal.tsx
  src/components/hoc/WithAccount.tsx
Labels: bug

#209 fix: stops re-checking funds upon successful purchase (rns)
  src/components/pages/rns/buy/DomainOffersCheckoutPage.tsx
Labels: P3 - Low, bug
