Repository rsksmart/rif-marketplace-ui, pull requests merged in 2020-09, with the labels that each got.

#329 fix: better types and collects marketplace props
  src/components/organisms/rns/sell/MyDomains.tsx
  src/components/organisms/rns/sell/MyOffers.tsx
  src/components/organisms/rns/sell/SoldDomains.tsx
  src/components/pages/rns/buy/DomainOffersPage.tsx
  src/components/templates/marketplace/Marketplace.tsx
Labels: P3 - Low, refactor

#374 fix: removes name from storage filters and uses provider
  src/api/models/storage/StorageFilter.ts
  src/components/organisms/filters/storage/StorageFilters.tsx
  src/models/marketItems/StorageFilters.ts
Labels: bug

#379 feat: get min/max AVG billing price in one call
  src/api/rif-marketplace-cache/storage/avg-billing-plan-price.ts
Labels: optimisation
