Repository rsksmart/rif-marketplace-ui, pull requests merged in 2020-07, with the labels that each got.

#210 refactor: normalises stores
  src/App.tsx
  src/api/models/RnsFilter.ts
  src/api/models/apiService.ts
  src/api/models/serviceAddresses.ts
  src/api/models/transports.ts
  src/api/rif-marketplace-cache/blockchain/confirmations.ts
  src/api/rif-marketplace-cache/cacheController.ts
  src/api/rif-marketplace-cache/config.ts
  src/api/rif-marketplace-cache/domainsController.ts
  src/api/rif-marketplace-cache/exchangeRateController.ts
  src/api/rif-marketplace-cache/rates/xr.ts
  src/api/rif-marketplace-cache/rns/common.ts
  src/api/rif-marketplace-cache/rns/domains.ts
  src/api/rif-marketplace-cache/rns/offers.ts
  src/api/rif-marketplace-cache/rns/sold.ts
  src/blockchain/config.ts
  src/components/Routes.tsx
  src/components/organisms/TransactionInProgressPanel.tsx
  src/components/organisms/filters/DomainFilters.tsx
  src/components/organisms/filters/DomainOffersFilters.tsx
  src/components/organisms/filters/SearchFilter.tsx
  src/components/organisms/rns/sell/MyDomains.tsx
  src/components/organisms/rns/sell/MyOffers.tsx
  src/components/organisms/rns/sell/SoldDomains.tsx
  src/components/pages/rns/buy/DomainOffersCheckoutPage.tsx
  src/components/pages/rns/buy/DomainOffersPage.tsx
  src/components/pages/rns/buy/DomainPurchased.tsx
  src/components/pages/rns/cancel/CancelDomainCheckoutPage.tsx
  src/components/pages/rns/cancel/DomainCanceled.tsx
  src/components/pages/rns/sell/DomainCheckoutPage.tsx
  src/components/pages/rns/sell/DomainListed.tsx
  src/components/pages/rns/sell/SellDomainsListPage.tsx
  src/components/templates/CheckoutPageTemplate.tsx
  src/components/templates/MarketPageTemplate.tsx
  src/components/templates/TxCompletePageTemplate.tsx
  src/components/templates/marketplace/MarketFilter.tsx
  src/components/templates/marketplace/Marketplace.tsx
  src/models/Market.ts
  src/models/marketItems/DomainItem.ts
  src/models/marketItems/StorageItem.ts
  src/store/App/AppStore.tsx
  src/store/App/appActions.ts
  src/store/App/appReducer.ts
  src/store/Blockchain/BlockchainStore.tsx
  src/store/Blockchain/blockchainActions.ts
  src/store/Blockchain/blockchainReducer.ts
  src/store/Market/MarketStore.tsx
  src/store/Market/marketActions.ts
  src/store/Market/marketReducer.ts
  src/store/Market/rns/DomainsStore.tsx
  src/store/Market/rns/OffersStore.tsx
  src/store/Market/rns/SoldStore.tsx
  src/store/Market/rns/interfaces.ts
  src/store/Market/rns/rnsActions.ts
  src/store/Market/rns/rnsReducer.ts
  src/store/Market/rns/utils.ts
  src/store/storeUtils/interfaces.ts
  src/store/storeUtils/reducer.ts
  src/utils/typeUtils.ts
Labels: enhancement

#251 feat: adds more accurate representation of price
  package-lock.json
  package.json
  src/api/models/transports.ts
  src/api/rif-marketplace-cache/rns/domains.ts
  src/api/rif-marketplace-cache/rns/offers.ts
  src/api/rif-marketplace-cache/rns/sold.ts
  src/components/organisms/rns/sell/MyOffers.tsx
  src/components/organisms/rns/sell/SoldDomains.tsx
  src/components/pages/rns/buy/DomainOffersPage.tsx
  src/models/marketItems/DomainItem.ts
  src/utils/parsers.ts
Labels: P0 - Critical

#265 fix: checks domain name before using it
  src/components/pages/rns/buy/DomainOffersCheckoutPage.tsx
  src/components/pages/rns/cancel/CancelDomainCheckoutPage.tsx
  src/components/pages/rns/sell/DomainCheckoutPage.tsx
Labels: bug
