Repository rsksmart/rif-marketplace-ui, pull requests merged in 2020-12, with the labels that each got.

#564 fix(storage-buy): resets periods and selected plan on currency change
  src/context/storage/buy/checkout/actions.ts
Labels: bug

#565 fix: removes duplicated config file
  src/api/rif-marketplace-cache/rns/common.ts
  src/blockchain/config.ts
Labels: refactor

#566 refactor(storage): changes non-active to withInactive
  src/api/models/storage/StorageFilter.ts
  src/components/organisms/storage/sell/OfferCreation.tsx
  src/components/pages/storage/myoffers/StorageMyOffersPage.tsx
  src/models/marketItems/StorageFilters.ts
Labels: refactor

#584 fix(storage-buy): avoids reseting done status on success
  src/context/storage/buy/checkout/Context.tsx
Labels: bug

#583 fix(storage-purchases): enables scroll view on purchases table
  src/components/pages/storage/myPurchases/Page.tsx
Labels: bug

#621 fix(design): avoids new line on ItemWUnit
  src/components/atoms/ItemWUnit.tsx
Labels: refactor, visual
