Repository rsksmart/rif-marketplace-ui, pull requests merged in 2020-05, with the labels that each got.

#103 fix: fixes domains controller tokens setup
  src/api/rif-marketplace-cache/domainsController.ts
Labels: bug, critical

#116 fix: makes sold domains searchable
  src/api/rif-marketplace-cache/domainsController.ts
  src/components/pages/rns/sell/SoldDomainsPage.tsx
Labels: bug

#131 Firefox compatibility
  package-lock.json
  package.json
  src/components/Routes.tsx
  src/components/organisms/filters/DomainOffersFilters.tsx
  src/components/pages/LandingPage.tsx
  src/components/pages/faq/FAQPage.tsx
  src/components/pages/index.ts
  src/components/pages/rns/buy/DomainOffersCheckoutPage.tsx
  src/components/pages/rns/buy/DomainOffersPage.tsx
  src/components/pages/rns/buy/index.ts
  src/components/pages/rns/index.ts
  src/components/pages/rns/sell/DomainCheckoutPage.tsx
  src/components/pages/rns/sell/MyDomainsPage.tsx
  src/components/pages/rns/sell/SoldDomainsPage.tsx
  src/components/pages/rns/sell/index.ts
Labels: bug, dependencies

#143 feat: fixes sold domains transport mapper
  src/api/rif-marketplace-cache/domainsController.ts
Labels: P1 - High, bug

#145 fix: fixed text spacing on storage page
  src/components/pages/storage/StoragePage.tsx
Labels: bug

#147 refactor: adapted to rif-ui library changes
  package-lock.json
  package.json
  src/components/organisms/Header.tsx
  src/components/organisms/ServiceCategories.tsx
  src/components/organisms/TransactionInProgressPanel.tsx
  src/components/organisms/filters/SearchFilter.tsx
  src/components/pages/rns/buy/DomainOffersCheckoutPage.tsx
  src/components/pages/rns/cancel/CancelDomainCheckoutPage.tsx
  src/components/pages/rns/sell/DomainCheckoutPage.tsx
  src/components/pages/rns/sell/MyDomainsPage.tsx
  src/components/templates/CheckoutPageTemplate.tsx
  src/components/templates/MarketPageTemplate.tsx
  src/components/templates/SideImageTemplate.tsx
  src/components/templates/marketplace/MarketFilter.tsx
  src/components/templates/marketplace/Marketplace.tsx
Labels: refactor
